# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: xSilo Quality Test

env:
  FOUNDRY_PROFILE: x_silo
  RPC_MAINNET: ${{ secrets.RPC_MAINNET }}
  RPC_ARBITRUM: ${{ secrets.RPC_ARBITRUM }}
  RPC_OPTIMISM: ${{ secrets.RPC_OPTIMISM }}
  RPC_SONIC: ${{ secrets.RPC_SONIC }}
  RPC_ANVIL: ${{ secrets.RPC_ANVIL }}
  PRIVATE_KEY: ${{ secrets.ANVIL_PRIVATE_KEY }}

on:
  push:
    branches: [ master, develop ]
    paths:
      - x-silo/**/*.sol
      - x-silo/**/*.ts
      - x-silo/**/*.js
      - x-silo/**/*.json
      - package.json
      - yarn.lock
      - gitmodules/*
      - .gitmodules
      - .github/workflows/x-silo.yml

  pull_request:
    paths:
      - x-silo/**/*.sol
      - x-silo/**/*.ts
      - x-silo/**/*.js
      - x-silo/**/*.json
      - package.json
      - yarn.lock
      - gitmodules/*
      - .gitmodules
      - .github/workflows/x-silo.yml

jobs:

  linters:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'

      - run: yarn install

      - name: Solidity Lint
        run: yarn workspace x-silo lint:sol

  foundry:
    name: Foundry QA
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Build silo foundry utils
        working-directory: ./gitmodules/silo-foundry-utils
        run: |
          cargo build --release
          cp target/release/silo-foundry-utils ../../silo-foundry-utils
          ../../silo-foundry-utils --version

      - name: Run Forge build
        run: |
          git submodule
          forge --version
          FOUNDRY_PROFILE=x_silo forge build --sizes

      - name: Run Forge tests
        run: FOUNDRY_PROFILE=x_silo forge test -vv --no-match-test "_skip_" --ffi
