[project]
name = "br1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "browser-use>=0.5.2",
    "dotenv>=0.9.9",
    "rich>=14.0.0",
]
