[project]
name = "n1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "gradio>=5.34.0",
    "huggingface-hub>=0.33.0",
    "openai>=1.86.0",
    "rich>=14.0.0",
]
