[invariant]

[profile.default]
libs = [
    'gitmodules',
    'node_modules',
]
out = 'cache/foundry/out'
evm_version = 'cancun'
gas_limit = '40000000000'
optimizer = true
optimizer_runs = 200
via_ir = false
allow_internal_expect_revert = true
always_use_create_2_factory = true

[profile.core]
src = 'silo-core/contracts'
out = 'cache/foundry/out/silo-core'
broadcast = 'silo-core/broadcast'

fs_permissions = [
    { access = "read", path = "./cache/foundry/"},
    { access = "read", path = "./silo-core/test/foundry/data/"},
    { access = "read", path = "./silo-core/deploy/input/"},
    { access = "read", path = "./silo-core/deploy/silo/_siloImplementations.json"}
]

[profile.core_with_test]
src = 'silo-core/contracts'
test = 'silo-core/test/foundry'
out = 'cache/foundry/out/silo-core'
broadcast = 'silo-core/broadcast'

fs_permissions = [
    { access = "read", path = "./cache/foundry/"},
    { access = "read", path = "./silo-core/test/foundry/data/"},
    { access = "read", path = "./silo-core/deploy/input/"},
    { access = "read", path = "./silo-core/deploy/silo/_siloDeployments.json"},
    { access = "read", path = "./silo-core/deploy/silo/_siloImplementations.json"}
]

[profile.core-with-invariants]
src = 'silo-core/contracts'
test = 'silo-core/test/invariants'
out = 'cache/foundry/out/silo-core'
broadcast = 'silo-core/broadcast'

fs_permissions = [
    { access = "read", path = "./cache/foundry/"},
    { access = "read", path = "./silo-core/test/foundry/data/"},
    { access = "read", path = "./silo-core/deploy/input/"}
]

[profile.core_test]
src = 'silo-core/test'
out = 'cache/foundry/out/silo-core'
broadcast = 'silo-core/broadcast'

fs_permissions = [
    { access = "read", path = "./cache/foundry/"},
    { access = "read", path = "./silo-core/test/foundry/data/"},
    { access = "read", path = "./silo-core/deploy/input/"},
    { access = "read", path = "./silo-core/deploy/silo/_siloDeployments.json"},
    { access = "read", path = "./silo-core/deploy/silo/_siloImplementations.json"}
]

[profile.default.fmt]
line_length=119

[profile.vaults]
src = 'silo-vaults/contracts'
out = 'cache/foundry/out/silo-vaults'
broadcast = 'silo-core/broadcast'

fs_permissions = [
    { access = "read", path = "./cache/foundry/"},
    { access = "read", path = "./silo-core/test/foundry/data/"},
    { access = "read", path = "./silo-core/deploy/input/"}
]

[profile.vaults_tests]
src = 'silo-vaults/test/foundry'
out = 'cache/foundry/out/silo-vaults'
broadcast = 'silo-vaults/broadcast'

fs_permissions = [
    { access = "read", path = "./cache/foundry/"},
    { access = "read", path = "./silo-core/test/foundry/data/"},
    { access = "read", path = "./silo-core/deploy/input/"}
]

[profile.vaults_with_tests]
src = 'silo-vaults/contracts'
test = 'silo-vaults/test/foundry'
out = 'cache/foundry/out/silo-vaults'
broadcast = 'silo-core/broadcast'

fs_permissions = [
    { access = "read", path = "./cache/foundry/"},
    { access = "read", path = "./silo-core/test/foundry/data/"},
    { access = "read", path = "./silo-core/deploy/input/"}
]

[profile.x_silo]
src = 'x-silo/contracts'
test = 'x-silo/test/foundry'
out = 'cache/foundry/out/x-silo'
broadcast = 'x-silo/broadcast'

[profile.x_silo_tests]
src = 'x-silo/test/foundry'
out = 'cache/foundry/out/x-silo'
broadcast = 'x-silo/broadcast'

[profile.x_silo_echidna]
src = 'x-silo/contracts'
test = 'x-silo/test/echidna'
out = 'cache/foundry/out/x-silo'
broadcast = 'x-silo/broadcast'

fs_permissions = [
    { access = "read", path = "./cache/foundry/"}
]

[profile.oracles]
src = 'silo-oracles/contracts'
out = 'cache/foundry/out/silo-oracles'
test = 'silo-oracles/test'
broadcast = 'silo-oracles/broadcast'

[fuzz]
max_test_rejects = 131072 # 65536 * 2 (doubled a default value)

[rpc_endpoints]
mainnet = "${RPC_MAINNET}"
sepolia = "${RPC_SEPOLIA}"
arbitrum_one = "${RPC_ARBITRUM}"
optimism = "${RPC_OPTIMISM}"
anvil = "${RPC_ANVIL}"
sonic = "${RPC_SONIC}"
ink = "${RPC_INK}"

[etherscan]
sonic = { key = "${VERIFIER_API_KEY_SONIC}", chain = 146, url = "${VERIFIER_URL_SONIC}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
